#spring:
#  application:
#    name: gateway
#
#  #网关配置
#  cloud:
#    gateway:
#      routes:
#        - id: nacos-consumer-a
#          uri: lb://sa
#          predicates:
#            - Path=/sa/**
#
#
#        - id: nacos-consumer-b
#          uri: lb://nacos-consumer-b
#          predicates:
#            - Path=/nacos-consumer-b/**
#      filters:
#        - StripPrefix=1
#      discovery:
#        locator:
#          enabled: true
